name: 'example'
description: 'Example application for the form_validation library'
version: '1.0.0+2'
publish_to: 'none'

environment: 
  sdk: '>=2.17.0 <3.0.0'

dependencies: 
  flutter: 
    sdk: 'flutter'
  form_floating_action_button: '^2.0.0+7'
  form_validation: 
    path: '../'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


flutter: 
  uses-material-design: true

ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
