name: 'form_validation'
description: 'Validators that can be used directly via code or constructed from JSON to provide  dynamic validation.'
version: '3.0.2+2'
homepage: 'https://github.com/peiffer-innovations/form_validation'

environment: 
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  flutter: 
    sdk: 'flutter'
  intl: '^0.18.1'
  json_class: '^2.2.2+1'
  meta: '^1.9.1'

dev_dependencies: 
  flutter_test: 
    sdk: 'flutter'


ignore_updates: 
  - 'archive'
  - 'async'
  - 'boolean_selector'
  - 'characters'
  - 'charcode'
  - 'collection'
  - 'clock'
  - 'crypto'
  - 'fake_async'
  - 'file'
  - 'matcher'
  - 'material_color_utilities'
  - 'meta'
  - 'path'
  - 'source_span'
  - 'stack_trace'
  - 'stream_channel'
  - 'string_scanner'
  - 'sync_http'
  - 'term_glyph'
  - 'test_api'
  - 'typed_data'
  - 'vector_math'
  - 'webdriver'
