name: form_validation
description: Validators that can be used directly via code or constructed from JSON to provide  dynamic validation.
version: 1.0.1
homepage: https://github.com/peiffer-innovations/form_validation

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  json_class: ^1.0.6
  meta: ^1.1.8
  static_translations: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
